import React from 'react';
import { storiesOf } from '@storybook/react';

import { SimpleSlider } from './Slider';

const data: any = [
    {
        adult: false,
        backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
        genre_ids: [12, 14, 10751, 16],
        id: 529203,
        original_language: 'en',
        original_title: 'The Croods: A New Age',
        overview:
            "After leaving their cave, the Croods encounter their biggest threat since leaving: another family called the Bettermans, who claim and show to be better and evolved. Grug grows suspicious of the Betterman parents, Phil and Hope,  as they secretly plan to break up his daughter Eep with her loving boyfriend Guy to ensure that their daughter Dawn has a loving and smart partner to protect her.  Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
        popularity: 2847.08,
        poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
        release_date: '2020-11-25',
        title: 'The Croods: A New Age',
        video: false,
        vote_average: 8,
        vote_count: 603,
    },
    {
        adult: false,
        backdrop_path: '/zbD96UExL9hl8TNihhs16vTBPEn.jpg',
        genre_ids: [878],
        id: 733317,
        original_language: 'en',
        original_title: 'Monsters of Man',
        overview:
            "A robotics company vying to win a lucrative military contract team up with a corrupt CIA agent to conduct an illegal live field test. They deploy four weaponized prototype robots into a suspected drug manufacturing camp in the Golden Triangle, assuming they'd be killing drug runners that no one would miss. Six doctors on a humanitarian mission witness the brutal slaughter and become prime targets.",
        popularity: 2583.204,
        poster_path: '/1f3qspv64L5FXrRy0MF8X92ieuw.jpg',
        release_date: '2020-11-19',
        title: 'Monsters of Man',
        video: false,
        vote_average: 7.6,
        vote_count: 76,
    },
    {
        adult: false,
        backdrop_path: '/tYkMtYPNpUdLdzGDUTC5atyMh9X.jpg',
        genre_ids: [28, 53, 80, 18],
        id: 553604,
        original_language: 'en',
        original_title: 'Honest Thief',
        overview:
            "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
        popularity: 2347.778,
        poster_path: '/zeD4PabP6099gpE0STWJrJrCBCs.jpg',
        release_date: '2020-09-03',
        title: 'Honest Thief',
        video: false,
        vote_average: 7,
        vote_count: 272,
    },
    {
        adult: false,
        backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
        genre_ids: [28, 53, 878],
        id: 577922,
        original_language: 'en',
        original_title: 'Tenet',
        overview:
            'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
        popularity: 1802.911,
        poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
        release_date: '2020-08-22',
        title: 'Tenet',
        video: false,
        vote_average: 7.4,
        vote_count: 3212,
    },
    {
        adult: false,
        backdrop_path: '/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg',
        genre_ids: [28, 53],
        id: 524047,
        original_language: 'en',
        original_title: 'Greenland',
        overview:
            "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
        popularity: 1435.481,
        poster_path: '/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg',
        release_date: '2020-07-29',
        title: 'Greenland',
        video: false,
        vote_average: 7.1,
        vote_count: 1072,
    },
    {
        adult: false,
        backdrop_path: '/wk58aoyWpMTVkKkdjw889XfWGdL.jpg',
        genre_ids: [53, 80, 9648],
        id: 646593,
        original_language: 'en',
        original_title: 'Wander',
        overview:
            "After getting hired to probe a suspicious death in the small town of Wander, a mentally unstable private investigator becomes convinced the case is linked to the same 'conspiracy cover up' that caused the death of his daughter.",
        popularity: 1401.505,
        poster_path: '/2AwPvNHphpZBJDqjZKVuMAbvS0v.jpg',
        release_date: '2020-12-04',
        title: 'Wander',
        video: false,
        vote_average: 5.5,
        vote_count: 44,
    },
    {
        adult: false,
        backdrop_path: '/jeAQdDX9nguP6YOX6QSWKDPkbBo.jpg',
        genre_ids: [28, 14, 878],
        id: 590706,
        original_language: 'en',
        original_title: 'Jiu Jitsu',
        overview:
            'Every six years, an ancient order of jiu-jitsu fighters joins forces to battle a vicious race of alien invaders. But when a celebrated war hero goes down in defeat, the fate of the planet and mankind hangs in the balance.',
        popularity: 1381.294,
        poster_path: '/eLT8Cu357VOwBVTitkmlDEg32Fs.jpg',
        release_date: '2020-11-20',
        title: 'Jiu Jitsu',
        video: false,
        vote_average: 5.6,
        vote_count: 196,
    },
    {
        adult: false,
        backdrop_path: '/ckfwfLkl0CkafTasoRw5FILhZAS.jpg',
        genre_ids: [28, 35, 14],
        id: 602211,
        original_language: 'en',
        original_title: 'Fatman',
        overview:
            'A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.',
        popularity: 1319.576,
        poster_path: '/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg',
        release_date: '2020-11-13',
        title: 'Fatman',
        video: false,
        vote_average: 5.8,
        vote_count: 232,
    },
    {
        adult: false,
        backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
        genre_ids: [14, 28, 12],
        id: 464052,
        original_language: 'en',
        original_title: 'Wonder Woman 1984',
        overview:
            'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
        popularity: 1264.421,
        poster_path: '/lNVHB85FUDZqLzvug3k6FA07RIr.jpg',
        release_date: '2020-12-16',
        title: 'Wonder Woman 1984',
        video: false,
        vote_average: 7.5,
        vote_count: 334,
    },
    {
        adult: false,
        backdrop_path: '/lrzAb9QCwKPOwH1iY7WpfjR6jcC.jpg',
        genre_ids: [10770, 53],
        id: 648371,
        original_language: 'en',
        original_title: 'No Good Deed',
        overview:
            "Karen never planned on being a hero. A recent widow, she has her hands full with work and parenting her son Max. Then Karen saves Jeremy's life during a drug store robbery and quickly discovers that the young man is intent on paying her back at any cost. At first, life starts improving for this good Samaritan, but as Jeremy's efforts become more extreme, Karen starts to wonder if no good deed truly goes unpunished.",
        popularity: 1147.516,
        poster_path: '/27BnREBR5rcMrUVUhV5bTXlcCym.jpg',
        release_date: '2020-03-13',
        title: 'No Good Deed',
        video: false,
        vote_average: 5.8,
        vote_count: 11,
    },
    {
        adult: false,
        backdrop_path: '/zMcEalkxEiRjvmijliLBk0sYern.jpg',
        genre_ids: [35, 80, 53],
        id: 765123,
        original_language: 'de',
        original_title: 'Wir Können Nicht Anders',
        overview:
            "A man foils an attempted murder, then flees the crew of would-be killers along with their intended target as a woman he's just met tries to find him.",
        popularity: 1020.087,
        poster_path: '/ajKpYK7XdzIYjy9Uy8nkgRboKyv.jpg',
        release_date: '2020-12-04',
        title: 'Christmas Crossfire',
        video: false,
        vote_average: 4.3,
        vote_count: 35,
    },
    {
        adult: false,
        backdrop_path: '/8knaRrDd1FM1pbSLaViEQSxodi5.jpg',
        genre_ids: [18, 53],
        id: 441282,
        original_language: 'en',
        original_title: 'Night Hunter',
        overview:
            'A Minnesota police officer crosses paths with a committed and tireless vigilante as he follows the trail of a ruthless predator responsible for several abductions and murders.',
        popularity: 871.824,
        poster_path: '/vVYU0x9FRpiJNX7c54ciFnRBVYG.jpg',
        release_date: '2019-08-29',
        title: 'Night Hunter',
        video: false,
        vote_average: 6.5,
        vote_count: 394,
    },
    {
        adult: false,
        backdrop_path: '/cw8A0SprTxr7uSfcH7lwSRRhezJ.jpg',
        genre_ids: [12, 14, 28],
        id: 634244,
        original_language: 'en',
        original_title: "Heavenquest: A Pilgrim's Progress",
        overview:
            "Inspired by the 1678 novel The Pilgrim's Progress and an imagined prequel to Bunyan's original writings.  A regal man named Vangel is thrust on a journey against his will when he is suddenly and mysteriously arrested.  Injured and lost after escaping the dark king’s men, Vangel begins to have strange dreams and visions of a mysterious woman in white calling him from the unknown territory of the North.  Armed with a book called “The Record of the Ancients” that he receives from a wise sage named Elder, Vangel embarks on an adventure that takes him through treacherous mountain range, unending deserts, the Lake of Doubts, and the Forest of No Return.  Along the way, travel companions share about a fabled good king and his son in the North if he can make it there alive.",
        popularity: 801.451,
        poster_path: '/cLDPLia17AwMqSaRHccyAlInkch.jpg',
        release_date: '2020-07-13',
        title: "Heavenquest: A Pilgrim's Progress",
        video: false,
        vote_average: 5.5,
        vote_count: 35,
    },
    {
        adult: false,
        backdrop_path: '/sFLgXQGrSWxnjmPOpGKPApWNOUH.jpg',
        genre_ids: [36, 28, 12],
        id: 635237,
        original_language: 'en',
        original_title: 'Arthur & Merlin: Knights of Camelot',
        overview:
            'King Arthur returns home after fighting the Roman Empire. His illegitimate son has corrupted the throne of Camelot and King Arthur must reunite with the wizard Merlin and the Knights of the Round Table to fight to get back his crown.',
        popularity: 791.906,
        poster_path: '/chGTXsvn53XvEnvsJ9ZD9eiYKx9.jpg',
        release_date: '2020-05-28',
        title: 'Arthur & Merlin: Knights of Camelot',
        video: false,
        vote_average: 5.9,
        vote_count: 60,
    },
    {
        adult: false,
        backdrop_path: '/azTsf28VYj0rw6ql67fB8WnxbZX.jpg',
        genre_ids: [53, 27],
        id: 554585,
        original_language: 'es',
        original_title: 'Sin origen',
        overview: 'A group of arcanes enjoy fighting vampires.',
        popularity: 743.397,
        poster_path: '/77lI0btz8qkExY13MKXaPrf4cA6.jpg',
        release_date: '2020-10-25',
        title: 'Originless',
        video: false,
        vote_average: 5.7,
        vote_count: 23,
    },
    {
        adult: false,
        backdrop_path: '/d2UxKyaJ5GgzuHaSsWinFfv3g6L.jpg',
        genre_ids: [28, 27, 53],
        id: 581392,
        original_language: 'ko',
        original_title: '반도',
        overview:
            'A soldier and his team battle hordes of post-apocalyptic zombies in the wastelands of the Korean Peninsula.',
        popularity: 697.232,
        poster_path: '/sy6DvAu72kjoseZEjocnm2ZZ09i.jpg',
        release_date: '2020-07-15',
        title: 'Peninsula',
        video: false,
        vote_average: 6.9,
        vote_count: 937,
    },
    {
        adult: false,
        backdrop_path: '/tfxRXujXbi2esl8WLhdqzixjbIY.jpg',
        genre_ids: [],
        id: 669444,
        original_language: 'fr',
        original_title: 'Les chevaliers du fiel dynamitent 2019',
        overview: '',
        popularity: 660.433,
        poster_path: '/oh6AZL0nnQdnz8bazoDzTAVVHfB.jpg',
        release_date: '',
        title: 'Les chevaliers du fiel dynamitent 2019',
        video: false,
        vote_average: 3.7,
        vote_count: 3,
    },
    {
        adult: false,
        backdrop_path: '/2WrvzB383GtEeX7f34LkocTKajp.jpg',
        genre_ids: [27],
        id: 753926,
        original_language: 'en',
        original_title: 'Toys of Terror',
        overview:
            'A big family moves into a dusty old house in the snowy woods of Washington with hopes of it being a nice holiday escape. But the kids soon discover a stash of old toys that just so happen to belong to a creepy ghost boy. As stranger and stranger things start to happen, some of the kids begin to sense that something in the house is not quite right…',
        popularity: 599.157,
        poster_path: '/c6hmAgPVXxZHwMHfS9z3W2n9Gz9.jpg',
        release_date: '2020-10-18',
        title: 'Toys of Terror',
        video: false,
        vote_average: 5.5,
        vote_count: 45,
    },
    {
        adult: false,
        backdrop_path: '/wUoWinqMkMtW00liA8egUAcAldz.jpg',
        genre_ids: [27, 18, 14],
        id: 590995,
        original_language: 'en',
        original_title: 'The Craft: Legacy',
        overview:
            'An eclectic foursome of aspiring teenage witches get more than they bargained for as they lean into their newfound powers.',
        popularity: 565.895,
        poster_path: '/lhMIra0pqWNuD6CIXoTmGwZ0EBS.jpg',
        release_date: '2020-10-28',
        title: 'The Craft: Legacy',
        video: false,
        vote_average: 6.2,
        vote_count: 191,
    },
    {
        adult: false,
        backdrop_path: '/n1pNyAVAe0pJMwcTNYNwKGHXjVx.jpg',
        genre_ids: [14, 10751, 12, 35, 27],
        id: 531219,
        original_language: 'en',
        original_title: "Roald Dahl's The Witches",
        overview:
            "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
        popularity: 546.353,
        poster_path: '/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg',
        release_date: '2020-10-26',
        title: "Roald Dahl's The Witches",
        video: false,
        vote_average: 6.9,
        vote_count: 970,
    },
];

storiesOf('Slider', module).add('Movies', () => (
    <>
        <SimpleSlider data={data} rowTitle="New Movies" />
        <SimpleSlider data={data} rowTitle="Most Popular" />
    </>
));
